project:
  type: book
  resources: 
    - staticwebapp.config.json

book:
  title: "Super secure Quarto"
  author: "Dr. Albert Rapp"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

format:
  html:
    theme: cosmo



